#! /bin/sh

# Run sxhkd daemon
pgrep -x sxhkd > /dev/null || sxhkd &

# Run the eww bar
eww -c $HOME/.config/eww/mybar --restart open mybar &

# Run the picom
# picom --config $HOME/.config/picom/picom.conf &

# Run the power manager
xfce4-power-manager &

# Start some awesome wallpapers
feh --randomize --no-fehbg --bg-fill ~/Pictures/Wallpapers/*

# Set the cursor to the right way
xsetroot -cursor_name left_ptr

bspc monitor -d I II III IV V VI VII VIII IX X
bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^2' follow=on
